name: firstworkflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello, world!""
      - name: print goodbye
        run: 
          echo Add other actions to build,
          echo test, and deploy your project.